/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/Homepage/AboutSection.vue')['default']
    BlogCard: typeof import('./src/components/Homepage/BlogCard.vue')['default']
    BlogSection: typeof import('./src/components/Homepage/BlogSection.vue')['default']
    CustomContainer: typeof import('./src/components/CustomContainer.vue')['default']
    FeaturedProductCard: typeof import('./src/components/Homepage/FeaturedProductCard.vue')['default']
    FeaturedProducts: typeof import('./src/components/Homepage/FeaturedProducts.vue')['default']
    HeroSection: typeof import('./src/components/Homepage/HeroSection.vue')['default']
    MaterialPreview: typeof import('./src/components/Homepage/MaterialPreview.vue')['default']
    Navlink: typeof import('./src/components/Header/Navlink.vue')['default']
    NavlinkMobile: typeof import('./src/components/Header/NavlinkMobile.vue')['default']
    ProfessionalSection: typeof import('./src/components/Homepage/ProfessionalSection.vue')['default']
    ProfessionalSectionCard: typeof import('./src/components/Homepage/ProfessionalSectionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Header/Search.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
  }
}
